package br.maua.cic303;

import java_cup.runtime.*;

parser code {:
    // Método chamado pelo CUP quando encontra um erro sintático
    public void syntax_error(Symbol cur_token) {
        throw new RuntimeException(
            "Erro Sintático na linha "
            + cur_token.left
            + ", coluna "
            + cur_token.right
        );
    }
:}

/* ========================================================================= */
/* TERMINAIS                                                                 */
/* ========================================================================= */

terminal IF, THEN, ELSE, WHILE;
terminal ASSIGN, LPAREN, RPAREN, LBRACE, RBRACE, SEMI;

terminal String ID, NUMBER;
terminal String ADD_OP, MUL_OP, REL_OP;

/* ========================================================================= */
/* NÃO TERMINAIS                                                             */
/* ========================================================================= */

non terminal program;
non terminal stmt_list;
non terminal stmt;

non terminal assign_stmt;
non terminal if_stmt;
non terminal while_stmt;
non terminal block_stmt;
non terminal null_stmt;

non terminal expr;

/* ========================================================================= */
/* PRECEDÊNCIA                                                               */
/* ========================================================================= */

/* resolve dangling else */
precedence nonassoc ELSE;

/* matemática */
precedence left REL_OP;
precedence left ADD_OP;
precedence left MUL_OP;

/* ========================================================================= */
/* GRAMÁTICA                                                                 */
/* ========================================================================= */

start with program;

/* programa = lista de comandos */
program ::= stmt_list
          ;

/* lista recursiva */
/* IMPORTANTE: aceita vazio */
stmt_list ::= stmt_list stmt
            | stmt
            |
            ;

/* tipos de comando */
stmt ::= assign_stmt
       | if_stmt
       | while_stmt
       | block_stmt
       | null_stmt
       ;

/* atribuição */
assign_stmt ::= ID ASSIGN expr SEMI
              ;

/* if */
if_stmt ::= IF LPAREN expr RPAREN THEN stmt
          | IF LPAREN expr RPAREN THEN stmt ELSE stmt
          ;

/* while */
while_stmt ::= WHILE LPAREN expr RPAREN stmt
             ;

/* bloco */
block_stmt ::= LBRACE stmt_list RBRACE
             ;

/* comando nulo */
null_stmt ::= SEMI
            ;

/* expressões */
expr ::= expr ADD_OP expr
       | expr MUL_OP expr
       | expr REL_OP expr
       | LPAREN expr RPAREN
       | NUMBER
       | ID
       ;